####################################
# Automatically generated by SMake #
# https://github.com/kala13x/smake #
####################################

CXXFLAGS = -g -O2 -msse -mmmx -I./src -std=c++11
LIBS = -lpthread -lrt
NAME = ccdetect
ODIR = obj
OBJ = o

OBJS = qsync.$(OBJ) \
	qdvbts.$(OBJ) \
	qbuffer.$(OBJ) \
	qlogger.$(OBJ) \
	qtime.$(OBJ) \
	qsock.$(OBJ) \
	ccdetect.$(OBJ) \
	config.$(OBJ)

OBJECTS = $(patsubst %,$(ODIR)/%,$(OBJS))
INSTALL_BIN = /usr/bin
VPATH = ./src

.cpp.$(OBJ):
	@test -d $(ODIR) || mkdir -p $(ODIR)
	$(CXX) $(CXXFLAGS) -c -o $(ODIR)/$@ $< $(LIBS)

$(NAME):$(OBJS)
	$(CXX) $(CXXFLAGS) -o $(ODIR)/$(NAME) $(OBJECTS) $(LIBS)

.PHONY: install
install:
	@test -d $(INSTALL_BIN) || mkdir -p $(INSTALL_BIN)
	@install -m 0755 $(ODIR)/$(NAME) $(INSTALL_BIN)/

.PHONY: clean
clean:
	$(RM) $(ODIR)/$(NAME) $(OBJECTS)
